typography_spectrum: 0.8943323837593198
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.6949199778027833
  lightness: 0.5774019684176892
  saturation: 0.5793756139464676
  rhythmicContrast: 0.03699183464050293
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92749
analytics:
  google: UA-82318010-1
  facebook: null
  twitter: null
name: imij
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: /əˈbout/
    id: 1c84b21d-c2bb-4320-b65d-a0d74c3ee200
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d6f0b58-3acc-442d-8b6b-8294e06612b7.png
title: home
purpose: []
