layout_spectrum: 0.9767410552594811
typography_spectrum: 0.6278418500442058
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.19028891390189528
  lightness: 0.8688478057738394
  saturation: 0.15550084179267287
  rhythmicContrast: 0.6707407289650291
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-82318010-1
  facebook: null
  twitter: null
logo: null
name: /hōm/
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: /əˈbout/
    id: 1c84b21d-c2bb-4320-b65d-a0d74c3ee200
    type: content
  - name: /pôrtˈfōlēˌō/
    id: d1302b2b-9c26-4451-bcac-559a438cbf06
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d6f0b58-3acc-442d-8b6b-8294e06612b7.png
title: imij
purpose: []
